01_程式語言/Python/Python_Code/Web_Django/DjangoTest/DjangoTest/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import RedirectView
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

01_程式語言/Python/Python_Code/Web_Django/DjangoTest/catalog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('books', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('test', views.testpage, name='test'),
]

01_程式語言/Python/Python_Code/Web_Django/DjangoTest/catalog/models.py
from django.db import models
# Used to generate URLs by reversing the URL patterns
from django.urls import reverse
import uuid  # Required for unique book instances

# 書籍類型模型 (Genre model)


class Genre(models.Model):
    """Model representing a book genre."""
    # 這個模型是用來儲存書籍類型的資訊 — 例如：該本書是否為科幻小說、羅曼史、軍事歷史等。
    name = models.CharField(
        max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')

    def __str__(self):
        """String for representing the Model object."""
        return self.name

# 書本模型 (Book model)


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    # 這個 Book 模型一般來說代表一個可用書本的所有資訊，但並非包含特定的物理實例(physical instance)
    # 或者副本資訊(copy)，此模型使用 CharField 來表示書的 title 和 isbn (國際標準書號)(note how the
    # isbn specifies its label as "ISBN" using the first unnamed parameter
    # because the default label would otherwise be "Isbn").，另外此模型使用
    # TextField 來存 summary ，因為此文本可能會很長。
    title = models.CharField(max_length=200)
    # 作者(author)被宣告為外鍵(ForeignKey)，因此每本書只會有一名作者，但一名作者可能會有多本書
    # (實際上，一本書可能會有多名作者，不過這個案例不會有，所以在別的例子這種作法可能會有問題)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)

    # Foreign Key used because book can only have one author, but authors can
    # have multiple books
    # Author as a string rather than object because it hasn't been declared
    # yet in the file.
    summary = models.TextField(
        max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField(
        'ISBN', max_length=13, help_text='13 Character <a \
            href="https://www.isbn-international.org/content/what-isbn">\
            ISBN number</a>')

    # ManyToManyField used because genre can contain many books. Books can
    # cover many genres.
    # Genre class has already been defined so we can specify the object above.
    # 「書籍類別」(genre)是一個 ManyToManyField ，因此一本書可以有很多書籍類別，而一個書結類別也能夠對應到很多本書。
    genre = models.ManyToManyField(
        Genre, help_text='Select a genre for this book')

    def __str__(self):
        """String for representing the Model object."""
        return self.title
    # 回傳一個可以被用來存取該模型細節紀錄的 URL (要讓其有效運作，我們必須定義一個 URL 的映射，我們將其命名為 book-detail
    # ，另外還得定義一個關聯示圖(view)與模板(template) )。

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in
         Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])


# 書本詳情模型 (BookInstance model)


class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed
    from the library)."""
    # BookInstance 模型表示一個特定的書籍副本(可會被某人借走)，
    # 並且包含如「副本是否可用」、「預計歸還日期」、「版本說明」或「版本細節」等資訊，
    # 還有一個在圖書館中唯一的 id 。
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text='Unique ID for this particular \
                              book across whole library')
    # UUIDField 被用來將 id 字段再這個模型中設定為 primary_key，這類別的字段會分配一個全域唯一的值給每一個
    # 實例(instance)，也就是任何一本你能在圖書館找到的書。
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    # DateField 會被用來設定 due_back 的日期(紀錄書本何時會被歸還，可再被使用，或者是否正在保養期)，
    # 這個字段允許 blank 或 null 值，而當元數據模型 (Class Meta)收到請求(query)時
    # 也會使用此字段來做資料排序。

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )
    #  status 是一個 CharField 字段，用來定義一個選項列表。你可以看到，我們定義了一個包含「鍵-值對元組」
    # 的元組(tuple) 並使其成為選項的參數，鍵-值對中的值會陳列出來並可以被使用者選擇，當選項被選定後，鍵
    # (key)也會被儲存下來。我們也設定了預設的鍵值為 "m" (maintenance)
    # 用來表示當每本書在初始創造還未放上書架時是不可被使用的。
    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        """String for representing the Model object."""
        # 從 Python3.6 開始，你可以使用「字串插值語法」(又稱做 f-string)
        return f'{self.id} ({self.book.title})'

# 作者模型(Author model)


class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']
    # 反轉 author-detail 的URL映射，來獲得顯示單個作者的URL。
    # 無法直接在 list_display 中指定「書籍類別」(genre field)字段，因為它是一個 ManyToManyField
    # (多對多字段)，因為如果這樣做會造成很大的資料庫讀寫「成本」，所以 Django 會預防這樣的狀況發生，因此，取而代之，我們將定義一個
    # display_genre 函式以「字串」形式得到書籍類別。

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'


# 語言模型(Language model)
class Language(models.Model):
    name = models.CharField(
        max_length=200, help_text='Input the Language of book')

    def __str__(self):
        return self.name

01_程式語言/Python/Python_Code/Web_Django/DjangoTest/catalog/views.py
from django.shortcuts import render
from .models import Book, Author, BookInstance, Genre
from django.views import generic

# Create your views here.


def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(
        status__exact='a').count()

    # The 'all()' is implied by default.
    num_authors = Author.objects.count()

    num_genres = Genre.objects.count()

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_genres': num_genres,
    }

    # Render the HTML template index.html with the data in the context variable
    # 調用 render() 函數來創建並返回HTML頁面作為響應（此快捷功能包裝了許多其他函數，從而簡化了這種非常常見的用例）。
    # 它以原始 request 物件 (一個 HttpRequest)
    # 帶有數據佔位符的HTML模板以及上下文 context 變量包含將插入到這些佔位符中的數據的Python字典）為參數。
    return render(request, 'index.html', context=context)


def book_detail_view(request, pk):
    try:
        book = Book.objects.get(pk=pk)
    except Book.DoesNotExist as Http404:
        raise Http404('Book does not exist')

    # from django.shortcuts import get_object_or_404
    # book = get_object_or_404(Book, pk=primary_key)

    return render(request, 'book_detail.html', context={'book': book})


def testpage(request):
    book_test = Book.objects.all()
    context = {'book_test': book_test}
    return render(request, 'testpage.html', context=context)

# 通用view將查詢數據庫，以獲取指定模型（Book）的所有記錄


class BookListView(generic.ListView):
    model = Book
    paginate_by = 10
    # 添加屬性
    context_object_name = 'books'
    # # your own name for the list as a template variable
    # queryset = Book.objects.all()
    # # Get 5 books containing the title war
    template_name = 'book_list.html'
    # # Specify your own template name/location
    # # 覆寫某些類別方法

    # def get_queryset(self):
    #     # 列出其他用戶閱讀的前5本書，而不是列出所有書本。
    #     return Book.objects.all()

    def get_context_data(self, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)
        context['book_list'] = Book.objects.all()
        return context


class BookDetailView(generic.DetailView):
    model = Book
    template_name = 'book_detail.html'

    def book_detail_view(request, primary_key):
        try:
            book = Book.objects.get(pk=primary_key)
        except Book.DoesNotExist as Http404:
            raise Http404('Book does not exist')

        return render(request, 'catalog/book_detail.html', context={'book': book})

01_程式語言/Python/Python_Code/Web_Django/DjangoTest/catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}
    <title>Local Library</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Add additional CSS in static file 加載靜態文件後，您可以使用static 模板標籤，指定感興趣文件的相對URL。 -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
                {% block sidebar %}
                <ul class="sidebar-nav">
                    <!--引入了url 模板標籤。-->
                    <li><a href="{% url 'index' %}">Home</a></li>
                    <li><a href="{% url 'books' %}">All books</a></li>
                    <li><a href="">All authors</a></li>
                    <li><a href="{% url 'test' %}">Test Page</a></li>
                </ul>
                {% endblock %}
            </div>
            <div class="col-sm-10 ">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
</body>

</html>

01_程式語言/Python/Python_Code/Web_Django/DjangoTest/catalog/templates/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> 
  <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

01_程式語言/Python/Python_Code/Web_Django/DjangoTest/catalog/templates/book_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Book List</h1>
    {% if book_list %}
    <ul>
        {% for book in book_list %}
            <li>
                <a href='{{ book.get_absolute_url }}'>{{ book.title }}</a> ({{ book.author }})
            </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}

01_程式語言/Python/Python_Code/Web_Django/DjangoTest/catalog/templates/index.html
{% extends "base_generic.html" %}
{% block title %}<title>Test Index Title</title>{% endblock %}

{% block content %}
<h1>Local Library Home</h1>
<p>Welcome to LocalLibrary, a website developed by <em>Mozilla Developer Network</em>!</p>
<div>
    {% load static %}
    <img src="{% static "images/local_library_model_uml.png" %}" alt="My image" style="width:819px;height:523px;" />
</div>

<h2>Dynamic content</h2>
<p>The library has the following record counts:</p>
<ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
    <li><strong>Genres:</strong>{{ num_genres }}</li>
</ul>
{% endblock %}