01_程式語言/Python/Python_Code/Web_Django/Django_APIWeb/APIWeb_Django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Login.urls")),
    path('LineBot/', include("LineBot.urls")),
    path('Stock/', include("Stock.urls")),
    # media路徑配置
    url(r'media/(?P<path>.*)/$', serve,{'document_root': settings.MEDIA_ROOT}),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

01_程式語言/Python/Python_Code/Web_Django/Django_APIWeb/Login/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

# 避免路由硬編碼
app_name = "Login"
urlpatterns = [
    path('', views.index, name="login"),
    url(r'^verify/$', views.googleVerify),
    url(r'^user/$', views.userPage, name="user"),
    url(r'^main/$', views.mainPage, name="main"),
    url(r'^logout/$', views.logout, name="logout"),
    url(r'^useradd/$', views.useradd, name="useradd"),
    url(r'^useraddforms/$', views.useraddforms, name="useraddforms"),
    url(r'^useredit/$', views.useredit, name="useredit"),
    path('<id>/', views.usereditforms, name="usereditforms"),
    path('.well-known/pki-validation/5E2440DD33F318F86C43B03EA08B6B62.txt',
         views.txtPage),  # 驗證ssl證書用
    # url(r'^testpage/$', views.testPage, name="testpage"),
    # url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
]

01_程式語言/Python/Python_Code/Web_Django/Django_APIWeb/Stock/urls.py
from django.conf.urls import url
from . import views

app_name = "Stock"
urlpatterns = [
    url(r'^stock/$', views.stock, name='stock'),
]

01_程式語言/Python/Python_Code/Web_Django/Django_APIWeb/Login/models.py
from django.db import models
from django.contrib.auth.hashers import make_password
from django.utils import timezone
import pyotp
import qrcode
import uuid


class User(models.Model):
    account = models.CharField(max_length=20)
    password = models.CharField(max_length=30)
    accountID = models.UUIDField(default=uuid.uuid4)
    accountStateChoice = [
        ('Active', '正常'),
        ('Locked', '鎖定')
    ]
    accountState = models.CharField(
        max_length=10,
        choices=accountStateChoice,
        default='Active'
    )
    createDate = models.DateTimeField()
    lastEditDate = models.DateTimeField()
    googleSecret = models.CharField(max_length=50)
    googleQRCodeURL = models.TextField()
    loginStatusChoice = [
        ('online', '登入中'),
        ('offline', '未登入')
    ]
    loginStatus = models.CharField(
        max_length=10, choices=loginStatusChoice, default='offline')
    detial = models.TextField()

    def createUser(self, account, password):
        """創建帳號"""
        secret = pyotp.random_base32()
        imgQRCode = qrcode.make(pyotp.totp.TOTP(
            secret).provisioning_uri(account))
        imgQRCode.get_image().save(f"media/googleQRCode/{account}.png")
        addTemp = User(
            account=account,
            password=make_password(password),
            accountState='Active',
            createDate=timezone.now(),
            lastEditDate=timezone.now(),
            googleSecret=secret,
            googleQRCodeURL=f"media/googleQRCode/{account}.png",
            loginStatus='offline',
        )
        addTemp.save()

    def setRootAccount(self):
        """第一次開啟使用 建立root帳號"""
        if User.objects.filter(account="root").exists():
            pass
        else:
            User().createUser("root", "1qaz2wsx")

    def isLoggedIn(self, account):
        """判斷是否登入狀態"""
        accountData = User.objects.filter(account=account).get()
        if accountData.loginStatus == 'online':
            return True
        else:
            return False


class UserRecord(models.Model):
    recordID = models.UUIDField(primary_key=True)
    account = models.CharField(max_length=20)
    signInDataTime = models.DateTimeField()
    logOutDataTime = models.DateTimeField()

    def setSignInRecord(self, account):
        """創建登入紀錄"""
        addTemp = UserRecord(
            recordID=uuid.uuid1,
            account=account,
            signInDataTime=timezone.now(),
        )
        addTemp.save()

    def setLogOutRecord(self, account):
        """創建登出紀錄"""
        addTemp = UserRecord(
            account=account,
            logOutDataTime=timezone.now(),
        )
        addTemp.save()

01_程式語言/Python/Python_Code/Web_Django/Django_APIWeb/Stock/models.py
from django.db import models

# Create your models here.

01_程式語言/Python/Python_Code/Web_Django/Django_APIWeb/Login/forms.py
from django import forms


class addUserForm(forms.Form):
    '''新增使用者表單'''
    account = forms.CharField(label='帳號', max_length=20)
    account.widget.attrs.update({'class': 'form-control'})  # 套上css檔
    password = forms.CharField(
        label='密碼', max_length=30, widget=forms.PasswordInput)
    password.widget.attrs.update({'class': 'form-control'})  # 套上css檔


class editUserForm(forms.Form):
    '''編輯使用者表單'''
    default_account = ''
    account = forms.CharField(
        label='帳號', max_length=20, initial=default_account)
    account.widget.attrs.update({'class': 'form-control'})  # 套上css檔
    accountState = forms.ChoiceField(
        label='狀態', choices=[('Active', '正常'), ('Locked', '鎖定')], initial='Active')
    accountState.widget.attrs.update({'class': 'form-control'})
    detial = forms.CharField(label='備註')
    detial.widget.attrs.update({'class': 'form-control'})  # 套上css檔


class changePassword(forms.Form):
    password = forms.CharField(
        label='密碼', max_length=30, widget=forms.PasswordInput)
    password.widget.attrs.update({'class': 'form-control'})  # 套上css檔

01_程式語言/Python/Python_Code/Web_Django/Django_APIWeb/Login/views.py
from django.shortcuts import redirect, render, HttpResponse
from django.contrib.auth.hashers import check_password
from django.template.context_processors import csrf
from .forms import addUserForm, editUserForm
from .models import User
import pyotp
from datetime import datetime


def index(request):
    """首頁"""
    User().setRootAccount()  # 若無帳號建立第一個root帳號
    if 'ok' in request.GET:
        account = request.GET['account']
        password = request.GET['password']
        request.session['account'] = account
        if User.objects.filter(account=account).exists():
            dataPassword = User.objects.get(account=account)
            if check_password(password, dataPassword.password):
                request.session['is_login'] = None
                return redirect('verify/', account=account)
            else:
                return render(request, 'login.html', context={"message": "密碼錯誤"})
        else:
            return render(request, 'login.html', context={"message": "帳號不存在"})
    else:
        return render(request, 'login.html')


def googleVerify(request):
    """驗證碼頁面"""
    if 'veriftyok' in request.GET:
        verifty = request.GET['verifty']
        account = request.session['account']
        secret = User.objects.get(account=account).googleSecret
        if pyotp.totp.TOTP(secret).verify(verifty):
            request.session['is_login'] = True
            user = User.objects.filter(account=account).get()
            user.loginStatus = 'online'
            user.save()
            return redirect('/main/')
        else:
            return render(request, 'loginVerify.html', context={"message": "驗證碼錯誤"})
    else:
        return render(request, 'loginVerify.html')


def mainPage(request):
    '''主頁面'''
    try:
        if request.session['is_login'] != True:
            return redirect('/')
    except KeyError:
        return redirect('/')
    context = getAccount(request)
    context.update({'datetime': datetime.now()})
    return render(request, 'template.html', context=context)


def userPage(request):
    '''會員頁面'''
    try:
        if request.session['is_login'] != True:
            return redirect('/')
    except KeyError:
        return redirect('/')
    context = getAccount(request)
    context.update({'datetime': getTime()})
    userlist = User.objects.all()
    userdata = []
    for user in userlist:
        temp = {
            'id': user.id,
            'account': user.account,
            'accountID': user.accountID,
            'accountState': user.accountState,
            'createDate': user.createDate,
            'lastEditDate': user.lastEditDate,
            'googleQRCodeURL': user.googleQRCodeURL,
            'loginStatus': user.loginStatus,
            'detial': user.detial
        }
        userdata.append(temp)
    context.update({'userdata': userdata})
    return render(request, 'user.html', context=context)


def logout(request):
    '''登出動作'''
    request.session['is_login'] = False
    account = request.session['account']
    user = User.objects.filter(account=account).get()
    user.loginStatus = 'offline'
    user.save()
    return redirect('/')


def useraddforms(request):
    '''新增會員表單頁面'''
    try:
        if request.session['is_login'] != True:
            return redirect('/')
    except KeyError:
        return redirect('/')
    csrftoken = csrf(request)['csrf_token']  # 提供做csrftoken驗證
    addform = addUserForm(request.POST)
    context = {
        'csrftoken': csrftoken,
        'addform': addform
    }
    return render(request, 'useradd.html', context=context)


def usereditforms(request, id):
    '''編緝會員表單頁面'''
    try:
        if request.session['is_login'] != True:
            return redirect('/')
    except KeyError:
        return redirect('/')
    csrftoken = csrf(request)['csrf_token']  # 提供做csrftoken驗證
    user = User.objects.get(id=id)
    editform = editUserForm(request.POST)
    editform.default_account = user.account
    context = {
        'csrftoken': csrftoken,
        'editform': editform,
        'user': user
    }
    return render(request, 'useredit.html', context=context)


def useradd(request):
    '''處理新增會員操作'''
    if request.method == "POST":
        account = request.POST.get('account', '')
        password = request.POST.get('password', '')
        message = ''
        request.session['message'] = message
        if User.objects.filter(account=account).exists():
            message = '帳號已存在'
            return redirect('/useradd/', message=message)
        User().createUser(account, password)
        return redirect('/user/')


def useredit(request):
    '''處理編輯會員操作'''
    if request.method == "POST":
        account = request.POST.get('account', '')
    return HttpResponse()


def txtPage(request):
    '''驗證SSL'''
    return render(request, '5E2440DD33F318F86C43B03EA08B6B62.txt')


def getAccount(request):
    '''取得帳號'''
    account = request.session['account']
    return {'account': account}


def getTime():
    '''取得時間'''
    return str(datetime.now())[:-7]

01_程式語言/Python/Python_Code/Web_Django/Django_APIWeb/Stock/views.py
from django.shortcuts import render, redirect

# Create your views here.


def stock(request):
    try:
        if request.session['is_login'] != True:
            return redirect('/')
    except KeyError:
        return redirect('/')
    return render(request, 'stock.html')

def test(request):
    pass

01_程式語言/Python/Python_Code/Web_Django/Django_APIWeb/templates/login.html
<!doctype html> {% load static %}
<html>

<head>
    <!-- <link rel="stylesheet" href="{% static 'styles.css' %}"> -->
    <link rel="stylesheet" href="{% static 'stylesLogin.css' %}">
    <meta charset="utf-8">
    <title>登入</title>
</head>

<body>
    <div class="login-root">
        <div class="box-root flex-flex flex-direction--column" style="min-height: 100vh;flex-grow: 1;">
            <div class="box-root padding-top--24 flex-flex flex-direction--column" style="flex-grow: 1; z-index: 9;">
                <div class="formbg-outer">
                    <div class="formbg">
                        <div class="formbg-inner padding-horizontal--48">
                            <span class="padding-bottom--15">輸入你的帳號</span>
                            <form id="stripe-login" ,method="POST">
                                <div class="field padding-bottom--24">
                                    <label for="id_account">帳號</label>
                                    <input type="text" name="account" maxlength="20" required id="id_account">
                                </div>
                                <div class="field padding-bottom--24">
                                    <div class="grid--50-50">
                                        <label for="id_password">密碼</label>
                                    </div>
                                    <input type="password" name="password" required id="id_password">
                                </div>
                                <div class="field field-checkbox padding-bottom--24 flex-flex align-center">
                                    <h2 class="loginmessage">{{ message }}</h2>
                                </div>
                                <div class="field padding-bottom--24">
                                    <input type="hidden" name="ok">
                                    <input type="submit" value="登入">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

01_程式語言/Python/Python_Code/Web_Django/Django_APIWeb/templates/loginVerify.html
<!doctype html> {% load static %}
<html>

<head>
    <!-- <link rel="stylesheet" href="{% static 'styles.css' %}"> -->
    <link rel="stylesheet" href="{% static 'stylesLogin.css' %}">
    <meta charset="utf-8">
    <title>登入</title>
</head>

<body>
    <div class="login-root">
        <div class="box-root flex-flex flex-direction--column" style="min-height: 100vh;flex-grow: 1;">
            <div class="box-root padding-top--24 flex-flex flex-direction--column" style="flex-grow: 1; z-index: 9;">
                <div class="formbg-outer">
                    <div class="formbg">
                        <div class="formbg-inner padding-horizontal--48">
                            <span class="padding-bottom--15">輸入驗證碼</span>
                            <h2 class="loginmessage">{{ message }}</h2>
                            <form id="stripe-login" ,method="POST">
                                <div class="field padding-bottom--24">
                                    <label for="id_account">驗證碼</label>
                                    <input type="verifty" name="verifty" maxlength="10" required id="id_verifty">
                                </div>
                                <div class="field padding-bottom--24">
                                    <input type="hidden" name="veriftyok">
                                    <input type="submit" value="送出">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

01_程式語言/Python/Python_Code/Web_Django/Django_APIWeb/templates/stock 2.html
{% extends "template.html" %}
<!DOCTYPE html>{% load static %}
<html lang="en">


<body>
    {% block Mainnavitemactive %}
    <li>
    {% endblock Mainnavitemactive %}
    {% block Stocknavitemactive %}
    <li class="nav-item active">
    {% endblock Stocknavitemactive %}
    {% block pagename %}
    <p class="navbar-brand">Stock</p>
    {% endblock pagename %} 
    {% block content %}
    {% endblock content %}
</body>

</html>

01_程式語言/Python/Python_Code/Web_Django/Django_APIWeb/templates/stock.html
{% extends "template.html" %}
<!DOCTYPE html>{% load static %}
<html lang="en">


<body>
    {% block Mainnavitemactive %}
    <li>
    {% endblock Mainnavitemactive %}
    {% block Stocknavitemactive %}
    <li class="nav-item active">
    {% endblock Stocknavitemactive %}
    {% block pagename %}
    <p class="navbar-brand">Stock</p>
    {% endblock pagename %} 
    {% block content %}
    {% endblock content %}
</body>

</html>

01_程式語言/Python/Python_Code/Web_Django/Django_APIWeb/templates/template.html
<!DOCTYPE html>{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="../assets/img/favicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>練習</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <!-- CSS Files -->
    <link href="{% static '/assets/css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static '/assets/css/light-bootstrap-dashboard.css' %}" rel="stylesheet" />
</head>

<body>
    <div class="wrapper">
        <div class="sidebar" data-image="../assets/img/sidebar-5.jpg" data-color="blue">
            <!--
        Tip 1: You can change the color of the sidebar using: data-color="purple | blue | green | orange | red"

        Tip 2: you can also add an image using data-image tag
    -->
            <div class="sidebar-wrapper">
                <div class="logo">
                    <a href="javascript:;" class="simple-text">
                      API練習網站
                    </a>
                </div>
                <ul class="nav">
                    {% block Mainnavitemactive %}
                    <li class="nav-item active">
                    {% endblock Mainnavitemactive %}
                        <a class="nav-link" href={% url 'Login:main' %}>
                            {% comment %} <i class="nc-icon nc-icon nc-paper-2"></i> {% endcomment %}
                            <p>Main Page</p>
                        </a>
                    </li>
                    {% block Usernavitemactive %}
                    <li>
                    {% endblock Usernavitemactive %}
                        <a class="nav-link" href={% url 'Login:user' %}>
                            {% comment %} <i class="nc-icon nc-bell-55"></i> {% endcomment %}
                            <p>User Page</p>
                        </a>
                    </li>
                    {% block Stocknavitemactive %}
                    <li>
                    {% endblock Stocknavitemactive %}
                        <a class="nav-link" href={% url 'Stock:stock' %}>
                            {% comment %} <i class="nc-icon nc-bell-55"></i> {% endcomment %}
                            <p>Stock Page</p>
                        </a>
                    </li>
                    <li class="nav-item active active-pro">
                        <p class="nav-link active">{{ datetime }}</p>
                        {% comment %} <a class="nav-link active" href="javascript:;">
                            <i class="nc-icon nc-alien-33"></i>
                            <p>Upgrade plan</p>
                        </a> {% endcomment %}
                    </li>
                </ul>
            </div>
        </div>

        <div class="main-panel">
            <!-- Navbar -->
            <nav class="navbar navbar-expand-lg " color-on-scroll="500">
                <div class="container-fluid">
                {% block pagename %}
                    <p class="navbar-brand">Main</p>
                {% endblock pagename %}
                    <button href="" class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-bar burger-lines"></span>
                        <span class="navbar-toggler-bar burger-lines"></span>
                        <span class="navbar-toggler-bar burger-lines"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end" id="navigation">
                        <ul class="nav navbar-nav mr-auto">
                            <li class="nav-item">
                            </li>
                            <li class="dropdown nav-item">
                            </li>
                            <li class="nav-item">
                            </li>
                        </ul>
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="#pablo">
                                    <span class="no-icon">目前帳號：{{ account }}</span>
                                </a>
                            </li>
                            <li class="nav-item dropdown">
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" href="#">Action</a>
                                    <a class="dropdown-item" href="#">Another action</a>
                                    <a class="dropdown-item" href="#">Something</a>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                    <div class="divider"></div>
                                    <a class="dropdown-item" href="#">Separated link</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'Login:logout' %}">
                                    <span class="no-icon">Log out</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

            <!-- End Navbar -->
            <div class="content">
                <div class="container-fluid">
                    <div class="section">
                    {% block content %}
                    {% endblock content %}
                    </div>
                </div>
            </div>
            <footer class="footer">
                <div class="container-fluid">
                    <nav>
                        <ul class="footer-menu">
                            <li>
                                <a href="#">
                                    Home
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Company
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Portfolio
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Blog
                                </a>
                            </li>
                        </ul>
                        <p class="copyright text-center">
                            ©
                            <script>
                                document.write(new Date().getFullYear())
                            </script>
                            <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
                        </p>
                    </nav>
                </div>
            </footer>

        </div>
    </div>
</body>

</html>

01_程式語言/Python/Python_Code/Web_Django/Django_APIWeb/templates/user.html
{% extends "template.html" %}
<!DOCTYPE html>{% load static %}
<html lang="en">


<body>
    {% block Mainnavitemactive %}
    <li>
    {% endblock Mainnavitemactive %}
    {% block Usernavitemactive %}
    <li class="nav-item active">
    {% endblock Usernavitemactive %}
    {% block pagename %}
    <p class="navbar-brand">User</p>
    {% endblock pagename %} 
    {% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="card strpied-tabled-with-hover">
                <div class="card-header ">
                    <footer class="footer">
                        <div class="container-fluid">
                            <nav>
                                <ul class="footer-menu">
                                    <li>
                                        <button class="btn btn-info btn-fill pull-right" type='button' onclick="location.href={% url 'Login:useraddforms' %}">新增</button>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </footer>
                    <footer class="footer">
                        <div class="container-fluid">
                            <nav>
                                <ul class="footer-menu">
                                    <form action=# method='post'>
                                    {% csrf_token %}
                                        <li>
                                            <input type="text" class="form-control" placeholder="輸入帳號">
                                        </li>
                                        <li>
                                            <button class="btn btn-info btn-fill pull-right" type='submit'>搜尋</button>
                                        </li>
                                    </form>
                                </ul>
                            </nav>
                        </div>
                    </footer>

                    <h4 class="card-title">使用者</h4>
                    <p class="card-category">使用者資料</p>
                </div>
                <div class="card-body table-full-width table-responsive">
                    <table class="table table-hover table-striped">
                        <thead>
                            <th>ID</th>
                            <th>帳號</th>
                            <th>UUID</th>
                            <th>狀態</th>
                            <th>創建日期</th>
                            <th>最後編輯日期</th>
                            <th>QRCode</th>
                            <th>登入狀態</th>
                            <th>備註</th>
                        </thead>
                        <tbody>
                            {% for user in userdata%}
                            <tr>
                                <td>{{ user.id }}</td>
                                <td>{{ user.account }}</td>
                                <td>{{ user.accountID }}</td>
                                <td>{{ user.accountState }}</td>
                                <td>{{ user.createDate }}</td>
                                <td>{{ user.lastEditDate }}</td>
                                <td><img height=50px src={{ user.googleQRCodeURL }} /></td>
                                <td>{{ user.loginStatus }}</td>
                                <td>{{ user.detial }}</td>
                                <td>
                                    <button class="btn btn-info btn-fill pull-right" type='button' onclick="location.href={% url 'Login:usereditforms' id=user.id %}">編輯</button>
                                </td>
                            </tr>
                            {% endfor %}
                            {% comment %} onclick="location.href={% url 'Login:usereditforms' %}" {% endcomment %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    {% endblock content %}

    {% comment %} <script>
        popupFunc = function() {
            window.open('/useraddforms.html/', 'useraddforms', "status=1, height:300, width:300, toolbar=0, resizeable=1")
                //open(url, name, 視窗引數)，注意name不能重名
        };

        callback = function(city) {
            var opt = document.createElement('option');
            opt.innerText = city;
            opt.setAttribute('selected', 'selected');
            var selEle = document.getElementById('cityChoose');
            selEle.appendChild(opt);
        }
    </script> {% endcomment %}
</body>

</html>

01_程式語言/Python/Python_Code/Web_Django/Django_APIWeb/templates/useradd.html
{% extends "user.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

{% comment %} <head>
    <link href="{% static '/styles.css' %}" rel="stylesheet" />
</head> {% endcomment %}

<body>
{% block content %}
<div class="content">
    <div class="container-fluid ">
        <div class="row">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">新增使用者</h4>
                    </div>
                    <div class="card-body">
                        <form action="/useradd/" method="post"> 
                        {% comment %} action="/useradd/"  {% endcomment %}
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="card-header">
                                        <h4 class="card-title">{{ message }}</h4>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>帳號</label>
                                        {{ addform.account }}
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>密碼</label>
                                        {{ addform.password }}
                                    </div>
                                </div>
                            </div>
                            {% comment %} <input type='hidden' name='csrfmiddlewaretoken' value={{ csrftoken }}> {% endcomment %}
                            <button class="btn btn-info btn-fill pull-right" type='submit'>送出</button>
                            {% comment %} onclick="location.href={% url 'Login:useradd' %}" {% endcomment %}
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
</body>