01_程式語言/Python/Python_Code/Web_Django/Django_APIWeb/APIWeb_Django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Login.urls")),
    path('LineBot/', include("LineBot.urls")),
    path('Stock/', include("Stock.urls")),
    # media路徑配置
    url(r'media/(?P<path>.*)/$', serve,{'document_root': settings.MEDIA_ROOT}),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

01_程式語言/Python/Python_Code/Web_Django/Django_APIWeb/Login/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

# 避免路由硬編碼
app_name = "Login"
urlpatterns = [
    path('', views.index, name="login"),
    url(r'^verify/$', views.googleVerify),
    url(r'^user/$', views.userPage, name="user"),
    url(r'^main/$', views.mainPage, name="main"),
    url(r'^logout/$', views.logout, name="logout"),
    url(r'^useradd/$', views.useradd, name="useradd"),
    url(r'^useraddforms/$', views.useraddforms, name="useraddforms"),
    url(r'^useredit/$', views.useredit, name="useredit"),
    path('<id>/', views.usereditforms, name="usereditforms"),
    path('.well-known/pki-validation/5E2440DD33F318F86C43B03EA08B6B62.txt',
         views.txtPage),  # 驗證ssl證書用
    # url(r'^testpage/$', views.testPage, name="testpage"),
    # url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
]

01_程式語言/Python/Python_Code/Web_Django/Django_APIWeb/templates/oldpage/baseMenu.html
<!doctype html> {% load static %}
<html>

<head>
    <link href="{% static '/assets/css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static '/assets/css/light-bootstrap-dashboard.css' %}" rel="stylesheet" />
    {% comment %} <link rel="stylesheet" href="{% static 'styles.css' %}"> {% endcomment %}
    <meta charset="utf-8">
</head>

<body>
    <div class="formbg-inner padding-horizontal--48">
        <div class="basetop">
            {% block topbar %}
            <ol>
                <li class="basemenu"><a class="base" href="{% url 'Login:login' %}">登出系統</a></li>
                <li class="basemenu"><a class="base" href="{% url 'Login:main' %}">主頁面</a></li>
                <li class="basemenu"><a class="base" href="{% url 'Login:userPage' %}">使用者</a></li>
                <li class="basemenu"><a class="base" href="{% url 'Login:testpage' %}">測試頁面</a>
                </li>
            </ol>
            {% endblock %}
        </div>

</body>

<body>
    <div class="basetop">
        <ol class="basesubmenu">
            <li class="basesubmenu"><a class="base" href="">使用者資訊</a></li>
            <li class="basesubmenu"><a class="base" href="">使用者權限</a></li>
        </ol>
    </div>
</body>

<body>
    {% block content %}{% endblock %}
</body>

</html>

01_程式語言/Python/Python_Code/Web_Django/Django_APIWeb/templates/oldpage/basePage.html
{% extends "baseMenu.html" %} {% load static %}
<!doctype html>
<html>
{% block content %}

<head>
    <link href="{% static '/assets/css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static '/assets/css/light-bootstrap-dashboard.css' %}" rel="stylesheet" />
    {% comment %} <link rel="stylesheet" href="{% static 'styles.css' %}"> {% endcomment %}
    <meta charset="utf-8">
    <title>登入後基礎頁面</title>
</head>

<body>
    <div class="base">
        <h1>Welcome!~ {{ account }}</h1>
        <h1>基礎頁面</h1>
    </div>
</body>

{% endblock %}

</html>

01_程式語言/Python/Python_Code/Web_Django/Django_APIWeb/templates/oldpage/baseUser.html
{% extends "template.html" %} {% load static %}
<!doctype html>
<html>
{% block content %}

<head>
    <link href="{% static '/assets/css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static '/assets/css/light-bootstrap-dashboard.css' %}" rel="stylesheet" />
    {% comment %} <link rel="stylesheet" href="{% static 'styles.css' %}"> {% endcomment %}
    <meta charset="utf-8">
    <title>登入後基礎頁面</title>
</head>

<body>
    <div class="">
        <h1>User Page</h1>
    </div>
</body>

{% endblock %}

</html>

01_程式語言/Python/Python_Code/Web_Django/Django_APIWeb/templates/oldpage/login1.html
<!doctype html> {% load static %}
<html>

<head>
    <!-- <link rel="stylesheet" href="{% static 'styles.css' %}"> -->
    <link rel="stylesheet" href="{% static 'stylesLogin.css' %}">
    <meta charset="utf-8">
    <title>登入</title>
</head>

<body>
    <div class="login-root">
        <div class="box-root flex-flex flex-direction--column" style="min-height: 100vh;flex-grow: 1;">
            <div class="box-root padding-top--24 flex-flex flex-direction--column" style="flex-grow: 1; z-index: 9;">
                <div class="formbg-outer">
                    <div class="formbg">
                        <div class="formbg-inner padding-horizontal--48">
                            <span class="padding-bottom--15">輸入你的帳號</span>
                            <form action='.' id="stripe-login" ,method="POST">
                                <div class="field padding-bottom--24">
                                    {{ login_form.as_table }}
                                </div>
                                <div class="field field-checkbox padding-bottom--24 flex-flex align-center">
                                    <h2 class="loginmessage">{{ message }}</h2>
                                </div>
                                <div class="field padding-bottom--24">
                                    <input type='submit' value='登入'>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>